name: Notify Telegram ğŸš€

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          format: markdown
          message: |
            *ğŸ”” YANGLANISH XABARI*
            ------------------------------------
            *ğŸ“ Loyiha:* `${{ github.repository }}`
            *ğŸŒ¿ Branch:* `#${{ github.ref_name }}`
            *ğŸ‘¤ Muallif:* `${{ github.actor }}`
            
            *ğŸ“ Xabar:*
            _${{ github.event.head_commit.message }}_
            
            *ğŸ“Š Holat:* âœ… Muvaffaqiyatli yuklandi
            *ğŸ”— Havola:* [O'zgarishlarni ko'rish](${{ github.event.head_commit.url }})
            ------------------------------------
            *â° Vaqt:* ${{ github.event.head_commit.timestamp }}
